appstory8/urls.py
from django.urls import path
from .views import *
from story3.settings import DEBUG, STATIC_URL, STATIC_ROOT
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name='index'),
    path('cari/', panggilAPI, name="panggil"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('kosong/', views.kosong, name='kosong'),
    # dilanjutkan ...
]

story3/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('appstory1.urls')),
    path('story5/', include('appstory5.urls')),
    path('story6/', include('appstory6.urls')),
    path('story7/', include('appstory7.urls')),
    path('story8/', include('appstory8.urls')),
    path('story9/', include('appstory9.urls')),
]

appstory8/models.py
from django.db import models

# Create your models here.

appstory8/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    response = {}
    return render(request,"index8.html",response)

def panggilAPI(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    print(ret.content)

    data = json.loads(ret.content)
    return JsonResponse(data,safe=False)

appstory8/templates/index8.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href=" {% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajax</title>
</head>
<body style="background: #31B7FF;">
    <nav class="navbar navbar-expand-md fixed-top topbar-transparent">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:index' %}">Story 3</a>
                </li>
            </ul>
        </div>
    </nav> 
    <br>
    <h4 class="display-3" style="color:#FFF;margin-top: 75px; margin-bottom: 75px; margin-left: 30px; margin-right: 30px; text-align:center; font-family: 'Poppins', sans-serif; font-weight: 800;">Find Your Books Here</h4>

        <center>
        <section style="margin-top: 75px; margin-bottom: 75px; margin-left: 150px; margin-right: 150px">
        <form method="POST" style="">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="input-group mb-3">
                        <input id="keyword" type="text" class="form-control" placeholder="Nama buku..." name="q" aria-describedby="button-addon2">
                        <div class="input-group-append">
                        </div>
                      </div>
                </div>
            </div>
        </form>
        </section>
        </center>

        <center>
        <div id="hasil">

        </div>
        </center>

        <script type="text/javascript">
            $("#keyword").keyup( function(){
                var ketik = $("#keyword").val();
                $.ajax({
                    url : 'cari?q=' + ketik,
                    success : function(data){
                        var array_items = data.items;
                        console.log(array_items);
                        $("#hasil").empty();

                        for (i = 0; i < array_items.length; i++) {
                            var judul = array_items[i].volumeInfo.title;
                            var gambar = array_items[i].volumeInfo.imageLinks.smallThumbnail;
                            $("#hasil").append( '<div class="card" style="width: 18rem;"><img src="' + gambar 
                                + '" class="card-img-top" alt="..."><div class="card-body"><h5 class="card-title">' + judul 
                                    + '</h5><p class="card-text">Some quick example text to build on the card title and make up the bulk of the card content.</p><a href="#" class="btn btn-primary">Go somewhere</a></div></div><br>'                                
                            );
                        }
                    }
                });
            });
        </script>
</body>
</html>